### PR TITLE
Add a flag to skip test files

### PR DESCRIPTION
**Pull request by haleyrc**
This PR adds a flag to allow a user to easily skip test files during analysis for cases when the critical component is the code under test and not the tests themselves.

### CODE REVIEW

**Comment by sebastianst** [comment]
This would indeed be very helpful, please merge.

**Comment by haleyrc** [comment]
@sebastianst I'm pretty sure this repo is dead, but if you're interested I have this behavior implemented in my fork.

**Comment by sebastianst** [comment]
Oh indeed, last commit is from 2015. Any idea which `gocyclo` is used at goreportcard or code climate? Do you know of an active fork?

**Comment by haleyrc** [comment]
Not a clue, unfortunately. For disclosure's sake, I also wouldn't call my fork "active". If you do come across a well-maintained fork though, I would love to hear about it.

**Comment by bkielbasa** [comment]
Hi! I'm working on the alternative for this project https://github.com/bkielbasa/cyclop
If you want to contribute, just do it :) I'll be happy to hear about ideas and PRs.

**Comment by fzipp** [comment]
Fixed by 4a36b7d43972d5dd35bc5204f7314dcb8cc848e4: -ignore flag added

**Pull request closed without merging**
